### ISSUE TITLE
Ensure API key access has been revoked

### ISSUE THREAD

**Issue by aallbrig** [98mprice/sponsorship_remover#7]
Please ensure the your API key access has been revoked; generate a new key. Never post secrets publically.

**Comment by micah5** [comment]
Hi, yes, it should have been revoked already. I deleted the key yesterday- is it still working for you?

**Comment by aallbrig** [comment]
No, I was just digging through the commit log and my heart jumped when I saw a secret. I tested the key but it looked like it was disabled. I just wanted to call this out to ensure that the secret was 100% destroyed! Closing this issue.
